# Generated by Django 4.2.6 on 2023-12-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_especificacion_tipo_valor'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='colores_impresion',
            field=models.CharField(choices=[('4+4', 'A color en ambos lados'), ('4+1', 'A color al frente, reverso B/N'), ('4+0', 'A color al frente, nada al reverso'), ('1+1', 'B/N ambos lados'), ('1+0', 'B/N al frente, nada al reverso')], max_length=200),
        ),
        migrations.AlterField(
            model_name='detalleordenproductoespecificacion',
            name='fk_id_producto_especificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productoespecificacion'),
        ),
    ]
