# Generated by Django 4.2.6 on 2023-12-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcionEspecificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_especificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.especificacion')),
                ('fk_id_opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.opcion')),
            ],
        ),
    ]
