# Generated by Django 4.2.6 on 2023-12-03 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_opcion_opcionespecificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoespecificacion',
            name='fk_id_especificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.especificacion'),
        ),
    ]
