# Generated by Django 4.2.6 on 2023-12-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productoespecificacion_fk_id_especificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionNumerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.IntegerField()),
                ('valor_maximo', models.IntegerField()),
                ('intervalo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='opcionespecificacion',
            name='fk_id_especificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.especificacion'),
        ),
        migrations.AlterField(
            model_name='opcionespecificacion',
            name='fk_id_opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.opcion'),
        ),
        migrations.CreateModel(
            name='OpcionNumericaEspecificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_especificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.especificacion')),
                ('fk_id_opcion_numerica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.opcionnumerica')),
            ],
        ),
    ]
