# Generated by Django 4.2.6 on 2023-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_opcionnumerica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacion',
            name='tipo_valor',
            field=models.CharField(choices=[('booleano', 'Si o No'), ('int', 'Entero'), ('string', 'Cadena de texto')], max_length=200),
        ),
    ]
